### ISSUE TITLE
在这个框架下，我理解的状态

### ISSUE THREAD

**Issue by adminchen** [willerce/canku#10]
1、输菜单是件麻烦事，现在有两种情况
A)菜单是纯汉字
B）菜单是图片
我的想法是，看是否是借用手机拍照的功能，将图片放到该注册用户所属组，并更新；如果是汉字，看是否利用扫描的一些插件去识别，或者，后者变为添加语音输入功能（这个比较常见，也有api接口）

2如果餐库主页面是目前的状态（针对小范围，不超过5个餐厅的选择），建议排列做成大图，类似做成如图1所示样式
![Dribbble - Restaurant Widget by Ionut Zamfir](https://f.cloud.github.com/assets/2234629/92939/a17a6e0c-6601-11e2-8c87-752de2479586.png)
如果是超过10个的，建议带GIS圈范围或者搜索功能

**Comment by willerce** [comment]
都是非常棒的建议，在程序达到基本功能完美，易配置部署后，我们会进行这些的工作。

**Comment by layerssss** [comment]
#18 使用了HTML5 摄像头接口，手机支持的，离这个目标更近了！

**Comment by willerce** [comment]
话说咱们可以考虑整个手机版的出来了！

**Comment by layerssss** [comment]
俺对移动WEB布局无力啊，还是比较喜欢用Bootstrap内置的responsive布局。

**Comment by willerce** [comment]
明天就放假回家，过完年来搞。

**Comment by layerssss** [comment]
先搜集引用代码
- 添加到主屏幕 https://github.com/cubiq/add-to-homescreen/
- 隐藏导航栏 http://stackoverflow.com/questions/6011223/how-to-completely-hide-the-navigation-bar-in-iphone-html-5
- http://stackoverflow.com/questions/2338638/how-to-hide-url-bar-in-ipod-touch
