### ISSUE TITLE
注册时出错，控制台上没有任何有效错误提示！！

### ISSUE THREAD

**Issue by hfeeki** [willerce/canku#13]
怎么这个版本跟你们演示的版本不一样？？ 点击注册按钮后，原先输入的东西都不见了，而且没有任何提示！

**Comment by layerssss** [comment]
请稍候，我测试一下问题所在

**Comment by layerssss** [comment]
@hfeeki  童鞋你数据库没有开啊，去[下载个mongod](http://www.mongodb.org/downloads)， 然后运行在后台,就能注册了

**Comment by willerce** [comment]
@hfeeki 演示的版本没有更新过。

**Comment by layerssss** [comment]
呼叫 @willerce

在 2013-2-2，上午11:53，willerce notifications@github.com 写道：

@hfeeki https://github.com/hfeeki 演示的版本没有更新过。

—
Reply to this email directly or view it on
GitHubhttps://github.com/willerce/canku/issues/13#issuecomment-13024271.

**Comment by willerce** [comment]
@layerssss 神马情况？ canku.willerce.com 这个版本木有更新。更新一份上去吗？

**Comment by layerssss** [comment]
更新吧少年

在 2013-2-2，上午11:55，willerce notifications@github.com 写道：

@layerssss https://github.com/layerssss 神马情况？
canku.willerce.com这个版本木有更新。要更新一份上去吗？

—
Reply to this email directly or view it on
GitHubhttps://github.com/willerce/canku/issues/13#issuecomment-13024299.
