### ISSUE TITLE
Support Alipay AA?

### ISSUE THREAD

**Issue by tooooolong** [willerce/canku#3]
既然是集体订单当然可以AA收款啦， 解决零钱不够的问题
:smile:

**Comment by willerce** [comment]
是的，这是我们公司内部最需要解决的问题。
零钱不够，或者忘记付钱给今天代付的同事，这都是非常尴尬的。

支付宝好像还没有提供AA 的API。
目前还没有想到一种比较好、并且简单的方式来做这个。

大家有什么更好的思路吗？

**Comment by tooooolong** [comment]
目前也只能贴一个aa的地址在上面了 用户点击就跳转支付，
总金额也只能负责人自己去看。

**Comment by layerssss** [comment]
呼叫 @turingou ，这个能实现吗？

**Comment by guo-yu** [comment]
支付宝没有发起AA的api，目前只有即时到帐交易api可以为个人开发者提供

**Comment by layerssss** [comment]
@willerce 可以用填写个人支付主页的方式来实现，其他用户最起码可以看到 **为人民服务者** 的支付主页，然后点进去付款（靠自觉）。

**Comment by guo-yu** [comment]
有两种方式：
1. 我包装了一个场景化支付插件：http://anypay.im
2. 小秘密：AA收款现已支持get query ：
   https://shenghuo.alipay.com/transfer/aaCollect/fill.htm?sellectEmails=turingou@yahoo.com.cn多个用户用,分割

在 2013年3月6日星期三，Michael Yin notifications@github.com 写道：

> @willerce 可以用填写个人支付主页的方式来实现，其他用户最起码可以看到 为人民服务者 的支付主页，然后点进去付款（靠自觉）。
> 
> —
> Reply to this email directly or view it on GitHub.<
> https://github.com/notifications/beacon/le1rFsPJQp1NmP-0KQPzCRENJmkkRoIK9q7QjiHZaVxR75difA1ypDCQymXb7-Jr.gif

## 

郭宇 http://guoyu.me

**Comment by layerssss** [comment]
楼上的`2. ....`要火，贪心一把：金额和原因能填么？ @turingou

**Comment by guo-yu** [comment]
暂时还不行。。。

在 2013年3月6日星期三，Michael Yin notifications@github.com 写道：

> 楼上的2. ....要火，贪心一把：金额和原因能填么？
> 
> —
> Reply to this email directly or view it on GitHub.

## 

郭宇 http://guoyu.me
