### ISSUE TITLE
找回密码功能

### ISSUE THREAD

**Issue by willerce** [willerce/canku#5]
很多同事经常把自己的帐号密码给忘记了。

**Comment by iot** [comment]
我也时常把自己的账号给忘记

**Comment by willerce** [comment]
目前 @zs1621 已经完成了一个找回密码功能。

流程是：输入邮箱->确认邮箱地址存在后生成一个随机密码->将新的密码通过邮件发送给用户

这个流程可能需要进一步优化，生成一个随机码后生成链接发送给用户，用户点击链接后才开始修改密码。
