### ISSUE TITLE
添加美食后，对应的shop中并不显示

### ISSUE THREAD

**Issue by runningdemo** [willerce/canku#8]
![截图](https://f.cloud.github.com/assets/1857448/89415/728d9fc4-653e-11e2-82e6-3b6772db3c6b.png)

**Comment by willerce** [comment]
不仔细看说明的都是坏孩子。
https://github.com/willerce/canku#%E6%B7%BB%E5%8A%A0%E5%BA%97%E9%93%BA
分类说明：店铺菜单分类，格式：数字编号#分类名|数字编号#分类名|。例如：1#商务套餐|2#营养套餐|3#其它

把用户体验做得这么烂的我也是坏孩子。

**Comment by runningdemo** [comment]
嘛，的确我是有点不仔细。
